# TCL File Generated by Component Editor 23.1
# Tue Jan 07 17:03:04 CST 2025
# DO NOT MODIFY


# 
# interrupt_connections "interrupt_connections" v1.0
#  2025.01.07.17:03:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module interrupt_connections
# 
set_module_property DESCRIPTION ""
set_module_property NAME interrupt_connections
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME interrupt_connections
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL interrupt_connections
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file interrupt_connections.v VERILOG PATH interrupt_connections.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL interrupt_connections
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file interrupt_connections.v VERILOG PATH interrupt_connections.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point signals
# 
add_interface signals conduit end
set_interface_property signals associatedClock clock
set_interface_property signals associatedReset ""
set_interface_property signals ENABLED true
set_interface_property signals EXPORT_OF ""
set_interface_property signals PORT_NAME_MAP ""
set_interface_property signals CMSIS_SVD_VARIABLES ""
set_interface_property signals SVD_ADDRESS_GROUP ""

add_interface_port signals irqs new_signal Output 64


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

