# TCL File Generated by Component Editor 23.1
# Wed Jan 08 15:31:50 CST 2025
# DO NOT MODIFY


# 
# VROOM "VROOM" v1.0
#  2025.01.08.15:31:50
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module VROOM
# 
set_module_property DESCRIPTION ""
set_module_property NAME VROOM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME VROOM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CoreWrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CoreWrapper.sv SYSTEM_VERILOG PATH ../../../../src/CoreWrapper.sv TOP_LEVEL_FILE
add_fileset_file LSIC.sv SYSTEM_VERILOG PATH ../../../../src/LSIC.sv
add_fileset_file BRAM1.v VERILOG PATH ../../../../src/bluespec/BRAM1.v
add_fileset_file BRAM1BE.v VERILOG PATH ../../../../src/bluespec/BRAM1BE.v
add_fileset_file FIFO1.v VERILOG PATH ../../../../src/bluespec/FIFO1.v
add_fileset_file FIFO2.v VERILOG PATH ../../../../src/bluespec/FIFO2.v
add_fileset_file RegFile.v VERILOG PATH ../../../../src/bluespec/RegFile.v
add_fileset_file RevertReg.v VERILOG PATH ../../../../src/bluespec/RevertReg.v
add_fileset_file SizedFIFO.v VERILOG PATH ../../../../src/bluespec/SizedFIFO.v
add_fileset_file SyncFIFO.v VERILOG PATH ../../../../src/bluespec/SyncFIFO.v
add_fileset_file mkCache32.v VERILOG PATH ../../../../../build/hw/mkCache32.v
add_fileset_file mkICache.v VERILOG PATH ../../../../../build/hw/mkICache.v
add_fileset_file mkVROOM.v VERILOG PATH ../../../../../build/hw/mkVROOM.v
add_fileset_file UART_rx.sv SYSTEM_VERILOG PATH ../../../../src/spart/UART_rx.sv
add_fileset_file UART_tx.sv SYSTEM_VERILOG PATH ../../../../src/spart/UART_tx.sv
add_fileset_file queue.sv SYSTEM_VERILOG PATH ../../../../src/spart/queue.sv
add_fileset_file spart.sv SYSTEM_VERILOG PATH ../../../../src/spart/spart.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL CoreWrapper
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file CoreWrapper.sv SYSTEM_VERILOG PATH ../../../../src/CoreWrapper.sv
add_fileset_file LSIC.sv SYSTEM_VERILOG PATH ../../../../src/LSIC.sv
add_fileset_file BRAM1.v VERILOG PATH ../../../../src/bluespec/BRAM1.v
add_fileset_file BRAM1BE.v VERILOG PATH ../../../../src/bluespec/BRAM1BE.v
add_fileset_file FIFO1.v VERILOG PATH ../../../../src/bluespec/FIFO1.v
add_fileset_file FIFO2.v VERILOG PATH ../../../../src/bluespec/FIFO2.v
add_fileset_file RegFile.v VERILOG PATH ../../../../src/bluespec/RegFile.v
add_fileset_file RevertReg.v VERILOG PATH ../../../../src/bluespec/RevertReg.v
add_fileset_file SizedFIFO.v VERILOG PATH ../../../../src/bluespec/SizedFIFO.v
add_fileset_file SyncFIFO.v VERILOG PATH ../../../../src/bluespec/SyncFIFO.v
add_fileset_file mkCache32.v VERILOG PATH ../../../../../build/hw/mkCache32.v
add_fileset_file mkICache.v VERILOG PATH ../../../../../build/hw/mkICache.v
add_fileset_file mkVROOM.v VERILOG PATH ../../../../../build/hw/mkVROOM.v
add_fileset_file SimDebugSlave.v VERILOG PATH ../../../../tb/SimDebugSlave.v
add_fileset_file UART_rx.sv SYSTEM_VERILOG PATH ../../../../src/spart/UART_rx.sv
add_fileset_file UART_tx.sv SYSTEM_VERILOG PATH ../../../../src/spart/UART_tx.sv
add_fileset_file queue.sv SYSTEM_VERILOG PATH ../../../../src/spart/queue.sv
add_fileset_file spart.sv SYSTEM_VERILOG PATH ../../../../src/spart/spart.sv


# 
# parameters
# 
add_parameter SIMULATION BOOLEAN false ""
set_parameter_property SIMULATION DEFAULT_VALUE false
set_parameter_property SIMULATION DISPLAY_NAME SIMULATION
set_parameter_property SIMULATION WIDTH ""
set_parameter_property SIMULATION TYPE BOOLEAN
set_parameter_property SIMULATION UNITS None
set_parameter_property SIMULATION DESCRIPTION ""
set_parameter_property SIMULATION HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master av_waitrequest waitrequest Input 1
add_interface_port avalon_master av_readdata readdata Input 32
add_interface_port avalon_master av_readdatavalid readdatavalid Input 1
add_interface_port avalon_master av_response response Input 2
add_interface_port avalon_master av_writeresponsevalid writeresponsevalid Input 1
add_interface_port avalon_master av_burstcount burstcount Output 5
add_interface_port avalon_master av_writedata writedata Output 32
add_interface_port avalon_master av_address address Output 32
add_interface_port avalon_master av_write write Output 1
add_interface_port avalon_master av_read read Output 1
add_interface_port avalon_master av_byteenable byteenable Output 4


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point interrupts
# 
add_interface interrupts conduit end
set_interface_property interrupts associatedClock clock
set_interface_property interrupts associatedReset ""
set_interface_property interrupts ENABLED true
set_interface_property interrupts EXPORT_OF ""
set_interface_property interrupts PORT_NAME_MAP ""
set_interface_property interrupts CMSIS_SVD_VARIABLES ""
set_interface_property interrupts SVD_ADDRESS_GROUP ""

add_interface_port interrupts irqs new_signal Input 64


# 
# connection point uart_rx
# 
add_interface uart_rx conduit end
set_interface_property uart_rx associatedClock clock
set_interface_property uart_rx associatedReset ""
set_interface_property uart_rx ENABLED true
set_interface_property uart_rx EXPORT_OF ""
set_interface_property uart_rx PORT_NAME_MAP ""
set_interface_property uart_rx CMSIS_SVD_VARIABLES ""
set_interface_property uart_rx SVD_ADDRESS_GROUP ""

add_interface_port uart_rx uart_rx new_signal Input 1


# 
# connection point uart_tx
# 
add_interface uart_tx conduit end
set_interface_property uart_tx associatedClock clock
set_interface_property uart_tx associatedReset ""
set_interface_property uart_tx ENABLED true
set_interface_property uart_tx EXPORT_OF ""
set_interface_property uart_tx PORT_NAME_MAP ""
set_interface_property uart_tx CMSIS_SVD_VARIABLES ""
set_interface_property uart_tx SVD_ADDRESS_GROUP ""

add_interface_port uart_tx uart_tx new_signal Output 1

